### ISSUE TITLE
 `org`  in gh-edu but in `get` it is `organization`

### ISSUE THREAD

**Issue by crguezl** [gh-cli-for-education/gh-edu#14]
@GGCristo 

With the organization set:

```
➜ gh-edu git:(main) ✗ gh edu get -o
No option. doing nothing
```

In `gh-edu` the option is called `org` but in `get` it is `organization`. The inconsistency causes the option to be `false`

version:

```
➜ gh-edu git:(main) ✗ gh extension list | grep gh-edu
gh edu gh-cli-for-education/gh-edu 6ba2495d
```

**Comment by GGCristo** [comment]
Ups, sorry about that 5c5368eec0c403290332dbd3d730fbc4823472d4
